//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClsDatFlotillas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatChoferes
    {
        public int id { get; set; }
        public string users { get; set; }
        public string pass { get; set; }
        public string nombre { get; set; }
        public string apeidoP { get; set; }
        public string apeidoM { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string placa { get; set; }
        public string remolque1 { get; set; }
        public string remolque2 { get; set; }
        public string enviarA { get; set; }
    }
}
