//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClsDatFlotillas
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvioCorreos
    {
        public int id { get; set; }
        public string FrenosEstacionamiento { get; set; }
        public string FrenosMantenimiento { get; set; }
        public string DispositivosAcoplamiento { get; set; }
        public string EquipoDeUrgencia { get; set; }
        public string Bocina { get; set; }
        public string LucesYReflectores { get; set; }
        public string Retrovisores { get; set; }
        public string Direccion { get; set; }
        public string Neumaticos { get; set; }
        public string RuedasYLlantas { get; set; }
        public string Limpiaparabrisas { get; set; }
        public string Otro { get; set; }
        public string UbicacionDeInspeccion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> NoHayDefectos { get; set; }
    }
}
