//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClsDatFlotillas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbFlotillasCamionEntities : DbContext
    {
        public dbFlotillasCamionEntities()
            : base("name=dbFlotillasCamionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatEmpresas> CatEmpresas { get; set; }
        public virtual DbSet<CatEstados> CatEstados { get; set; }
        public virtual DbSet<CatUsuarios> CatUsuarios { get; set; }
        public virtual DbSet<Dispositivos> Dispositivos { get; set; }
        public virtual DbSet<EnvioCorreos> EnvioCorreos { get; set; }
        public virtual DbSet<reglasEstados> reglasEstados { get; set; }
        public virtual DbSet<sessionActiva> sessionActiva { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<CatChoferes> CatChoferes { get; set; }
        public virtual DbSet<estatusActivo> estatusActivo { get; set; }
        public virtual DbSet<SessionAppActiva> SessionAppActiva { get; set; }
    
        public virtual ObjectResult<spObtenerExtraccionEvents_Result> spObtenerExtraccionEvents(Nullable<System.DateTime> fecha, Nullable<int> idChofer)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("idChofer", idChofer) :
                new ObjectParameter("idChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerExtraccionEvents_Result>("spObtenerExtraccionEvents", fechaParameter, idChoferParameter);
        }
    
        public virtual ObjectResult<spObtenerExtraccionInformacion_Result> spObtenerExtraccionInformacion(Nullable<System.DateTime> fecha, Nullable<int> idChofer)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("idChofer", idChofer) :
                new ObjectParameter("idChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerExtraccionInformacion_Result>("spObtenerExtraccionInformacion", fechaParameter, idChoferParameter);
        }
    
        public virtual ObjectResult<spObtenerReloj_Result> spObtenerReloj(Nullable<int> idChofer)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("idChofer", idChofer) :
                new ObjectParameter("idChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerReloj_Result>("spObtenerReloj", idChoferParameter);
        }
    
        public virtual ObjectResult<spObtenerUsuario_Result> spObtenerUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerUsuario_Result>("spObtenerUsuario");
        }
    }
}
