//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClsDatFlotillas
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessionActiva
    {
        public int id { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string accessToken { get; set; }
        public string correo { get; set; }
        public string idUser { get; set; }
        public string keyUser { get; set; }
    }
}
